language: ruby
rvm:
- 2.3.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master
    - develop

sudo: required

before_install:
  - nvm install node
  - ruby -v

install:
  - gem install jekyll
  - npm install -g firebase

before_script:
  - jekyll build
script:
  - firebase deploy --token "$FIREBASE_TOKEN"
